{
 "title": "Flapjack",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cycles count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max by(session_id) (increase(cycles_total[$__rate_interval]))",
       "legendFormat": "{{session_id}}"
      }
     ]
    },
    {
     "title": "Cycles duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(session_id) (rate(cycles_seconds_duration_sum[$__rate_interval])) / max by(session_id) (rate(cycles_seconds_duration_count[$__rate_interval]))",
       "legendFormat": "{{session_id}}"
      }
     ]
    },
    {
     "title": "Strategy executions total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "max by(strategy, symbol, strategy_status) (increase(strategy_executions_total[$__rate_interval]))",
       "legendFormat": "{{strategy}} {{symbol}} {{strategy_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "max by(path, method) (increase(server_http_requests_total[$__rate_interval]))",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "HTTP Requests duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(method, path) (rate(server_http_request_duration_seconds_sum[$__rate_interval])) / max by(method, path) (rate(server_http_request_duration_seconds_count[$__rate_interval]))",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "WebSocket messages count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(published_topic) (rate(server_ws_messages_total[$__rate_interval]))",
       "legendFormat": "{{published_topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "max by(method, endpoint, identity_codename) (increase(exchange_http_requests_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{method}} {{endpoint}}"
      }
     ]
    },
    {
     "title": "HTTP Requests duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(method, endpoint, identity_codename) (rate(exchange_http_request_duration_seconds_sum[$__rate_interval])) / max by(method, endpoint, identity_codename) (rate(exchange_http_request_duration_seconds_count[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{method}} {{endpoint}}"
      }
     ]
    },
    {
     "title": "WebSocket messages count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(topic, identity_codename) (rate(exchange_ws_messages_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Candle Database insertions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "max by(symbol, identity_codename, event, interval) (increase(cache_candle_database_cache_insertions_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{symbol}} {{interval}} {{event}}"
      }
     ]
    },
    {
     "title": "Candle Memory insertions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "max by(symbol, identity_codename, event, interval) (increase(cache_candle_memory_cache_insertions_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{symbol}} {{interval}} {{event}}"
      }
     ]
    },
    {
     "title": "Candle Exchange uses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "max by(symbol, identity_codename, interval) (increase(cache_candle_exchange_uses_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{symbol}} {{interval}} "
      }
     ]
    },
    {
     "title": "Candle Memory uses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "max by(symbol, identity_codename, interval) (increase(cache_candle_memory_cache_uses_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{symbol}} {{interval}} "
      }
     ]
    },
    {
     "title": "Ticker Memory uses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "max by(symbol, identity_codename) (increase(cache_ticker_memory_cache_uses_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{symbol}}"
      }
     ]
    },
    {
     "title": "Ticker Memory insertions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "max by(symbol, identity_codename, ) (increase(cache_ticker_memory_cache_insertions_total[$__rate_interval]))",
       "legendFormat": "{{identity_codename}} {{symbol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "increase(database_queries_total[$__rate_interval])",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Queries duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(query) (rate(database_queries_seconds_duration_sum[$__rate_interval])) / max by(query) (rate(database_queries_seconds_duration_count[$__rate_interval]))",
       "legendFormat": "{{query}}"
      }
     ]
    }
   ]
  }
 ]
}