global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [flapjack:8985]
    basic_auth:
      username: admin
      password: AdminPass1!
