name: Docker

on:
  repository_dispatch:
    types: [build]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the ${{ env.REGISTRY }} registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/jellydator/${{ vars.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/jellydator/${{ vars.IMAGE_NAME }}:${{github.event.client_payload.version}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "FLAPJACK_VERSION=${{github.event.client_payload.version}}"
